// <auto-generated />
using System;
using DfESurveyTool.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace DfESurveyTool.Data.Migrations
{
    [DbContext(typeof(DfESurveyToolDbContext))]
    [Migration("20201116162300_InitialMigration")]
    partial class InitialMigration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("DfESurveyTool.Data.Models.MyModel", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTimeOffset>("LastUpdated")
                        .HasColumnType("datetimeoffset");

                    b.Property<int>("MyModelStatusId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(200)")
                        .HasMaxLength(200);

                    b.HasKey("ID");

                    b.HasIndex("MyModelStatusId");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("MyModel");
                });

            modelBuilder.Entity("DfESurveyTool.Data.Models.MyModelStatus", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(200)")
                        .HasMaxLength(200);

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("MyModelStatus");

                    b.HasData(
                        new
                        {
                            Id = 0,
                            Name = "New"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Processing"
                        },
                        new
                        {
                            Id = 10,
                            Name = "Complete"
                        },
                        new
                        {
                            Id = 99,
                            Name = "Error"
                        });
                });

            modelBuilder.Entity("DfESurveyTool.Data.Models.MyModel", b =>
                {
                    b.HasOne("DfESurveyTool.Data.Models.MyModelStatus", "Status")
                        .WithMany("MyModels")
                        .HasForeignKey("MyModelStatusId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
